# https://docs.dapr.io/reference/components-reference/supported-secret-stores/file-secret-store/
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: localfile-secret-store
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: "/tmp/secrets.json"
  - name: nestedSeparator
    value: ":"
  - name: multiValued
    value: "false"
